### ISSUE TITLE
Video 

### ISSUE THREAD

**Issue by himalacharya** [AdityaPai2398/Vehicle-And-Pedestrian-Detection-Using-Haar-Cascades#1]
Hi,
Can you provide me your video for bike and vehicle video file?
Himal

**Comment by AdityaPai2398** [comment]
Here you go!

https://drive.google.com/drive/folders/0BxMpNQBtGeFmNks4MDBpUmZFRlE?usp=sharing

**Comment by himalacharya** [comment]
Thank you for videos. Can you provide me your positive sample and negative samples? It will help me to make XML file. Can classifier file can be created in windows ?

Himal
