### ISSUE TITLE
About positive and negative samples

### ISSUE THREAD

**Issue by himalacharya** [AdityaPai2398/Vehicle-And-Pedestrian-Detection-Using-Haar-Cascades#2]
Thank you for videos. Can you provide me your positive sample and negative samples? It will help me to make XML file. Can classifier file can be created in windows ?

Himal

**Comment by AdityaPai2398** [comment]
I created the positive samples by taking screenshot of videos and downloading pics from Google(there are tools for downloading bulk images) and then cropping them.

Negative images were random grey scale images not containing the object intended to be detected.


Yes it's possible to train on Windows other options include training on cloud too if your system specs aren't good.(a cheap digitalocean server)
